# Generated by Django 2.0.4 on 2018-09-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('person', models.CharField(max_length=64, verbose_name='负责人')),
                ('status', models.BooleanField(choices=[(True, '已完成'), (False, '进行中')], default=False, verbose_name='状态')),
                ('priority', models.NullBooleanField(choices=[(True, '高'), (False, '中'), (None, '低')], default=None, verbose_name='优先级')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '任务记录',
                'verbose_name_plural': '任务记录',
            },
        ),
    ]
