# Generated by Django 2.0.4 on 2018-09-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need_fix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.TextField(max_length=255, verbose_name='内容'),
        ),
    ]
